on: push

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_REPOSITORY: kandler3/vvot-lab 
  DOCKER_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Setup Compose
      uses: docker/setup-compose-action@v1.2.0
          

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images using docker-compose
      run: |
        docker-compose -f compose.yaml build
        docker-compose -f compose.yaml push
